# Generated by Django 4.1.3 on 2022-12-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizanswer_options_alter_quizquestion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='quiz',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
            preserve_default=False,
        ),
    ]
