# Generated by Django 4.1.3 on 2022-12-04 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizanswer_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='quiz',
        ),
    ]
